### ISSUE TITLE
The dataset cannot be accessed

### ISSUE THREAD

**Issue by smile-114** [nv-nguyen/nope#15]
D:\Anaconda\envs\nope\python.exe D:\nh\nope-main\nope-main\test_shapeNet.py 
Global seed set to 2022
[2024-12-05 16:04:06,002][root][INFO] - Initializing logger, callbacks and trainer
[2024-12-05 16:04:06,002][__main__][INFO] - Initializing logger, callbacks and trainer
[2024-12-05 16:04:06,003][__main__][INFO] - Wandb logger initialized at ./nope_project//results/train_all
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: WARNING `resume` will be ignored since W&B syncing is set to `offline`. Starting a new run with run id z4wvwew8.
wandb: Tracking run with wandb version 0.18.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
ModelCheckpoint(save_last=True, save_top_k=-1, monitor=None) will duplicate the last checkpoint saved.
GPU available: True (cuda), used: True
[2024-12-05 16:04:06,564][root][INFO] - Trainer initialized
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2024-12-05 16:04:07,021][xformers][WARNING] - A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Error executing job with overrides: []
Traceback (most recent call last):
  File "D:\Anaconda\envs\nope\lib\site-packages\diffusers\models\modeling_utils.py", line 857, in _get_model_file
    model_file = hf_hub_download(
  File "D:\Anaconda\envs\nope\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "D:\Anaconda\envs\nope\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\Anaconda\envs\nope\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'runwayml\stable-diffusion-v1-5'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "D:\nh\nope-main\nope-main\src\models\encoder\AutoencoderKL.py", line 18, in __init__
    self.encoder = AutoencoderKL.from_pretrained(
  File "D:\Anaconda\envs\nope\lib\site-packages\diffusers\models\modeling_utils.py", line 527, in from_pretrained
    model_file = _get_model_file(
  File "D:\Anaconda\envs\nope\lib\site-packages\diffusers\models\modeling_utils.py", line 894, in _get_model_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like runwayml\stable-diffusion-v1-5 is not the path to a directory containing a file named diffusion_pytorch_model.bin or 
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\nh\nope-main\nope-main\test_shapeNet.py", line 92, in <module>
    test()
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\main.py", line 94, in decorated_main
    _run_hydra(
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\utils.py", line 394, in _run_hydra
    _run_app(
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\utils.py", line 457, in _run_app
    run_and_report(
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\utils.py", line 223, in run_and_report
    raise ex
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "D:\nh\nope-main\nope-main\test_shapeNet.py", line 48, in test
    model = instantiate(cfg.model)
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "D:\Anaconda\envs\nope\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.encoder.AutoencoderKL.VAE_StableDiffusion':
OSError("We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like runwayml\\stable-diffusion-v1-5 is not the path to a directory containing a file named diffusion_pytorch_model.bin or \nCheckout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.")
full_key: model.u_net.encoder
wandb:
wandb: You can sync this run to the cloud by running:
wandb: wandb sync ./nope_project//results/train_all/wandb\offline-run-20241205_160406-z4wvwew8

I have already downloaded the dataset from https://huggingface.co/datasets/nv-nguyen/nope locally, but the distribution of the dataset after extraction looks like this
![image](https://github.com/user-attachments/assets/cec5c8f3-e3c2-414a-8468-57a7c259839a)
![folder](https://github.com/user-attachments/assets/502e8563-8d65-4b4b-8379-217bcb99e2d3)

My folder arrangement does not match the arrangement provided by you. Can I ask where the problem occurred? Could you please help to explain? Thank you very much.

**Comment by smile-114** [comment]
![Uploading folder arrangement.PNG…]()
